# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, user_agent: str=None, ip_addr: str=None):  # noqa: E501
        """User - a model defined in Swagger

        :param user_id: The user_id of this User.  # noqa: E501
        :type user_id: int
        :param user_agent: The user_agent of this User.  # noqa: E501
        :type user_agent: str
        :param ip_addr: The ip_addr of this User.  # noqa: E501
        :type ip_addr: str
        """
        self.swagger_types = {
            'user_id': int,
            'user_agent': str,
            'ip_addr': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'user_agent': 'user_agent',
            'ip_addr': 'ip_addr'
        }
        self._user_id = user_id
        self._user_agent = user_agent
        self._ip_addr = ip_addr

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this User.


        :return: The user_id of this User.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this User.


        :param user_id: The user_id of this User.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def user_agent(self) -> str:
        """Gets the user_agent of this User.


        :return: The user_agent of this User.
        :rtype: str
        """
        return self._user_agent

    @user_agent.setter
    def user_agent(self, user_agent: str):
        """Sets the user_agent of this User.


        :param user_agent: The user_agent of this User.
        :type user_agent: str
        """

        self._user_agent = user_agent

    @property
    def ip_addr(self) -> str:
        """Gets the ip_addr of this User.


        :return: The ip_addr of this User.
        :rtype: str
        """
        return self._ip_addr

    @ip_addr.setter
    def ip_addr(self, ip_addr: str):
        """Sets the ip_addr of this User.


        :param ip_addr: The ip_addr of this User.
        :type ip_addr: str
        """

        self._ip_addr = ip_addr
